[package]
name = "snes-graph"
version = "0.2.4"
edition = "2021"
license = "MIT"
authors = ["David Brugneaux and contributors"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tempfile = "3"
serde = { version = "1", features = ["derive"] }

[profile.release]
strip = true
lto = true
codegen-units = 1
