-- Three animation modes and two characters, generated by verify-gallery.ts.
local dir=assert(os.getenv('SNES_GRAPH_TEST_OUTPUT'));local n=0
local function word(a)return emu.read(a,emu.memType.snesWorkRam)+256*emu.read(a+1,emu.memType.snesWorkRam)end
local steps={[20]={a=true},[50]={a=true},[60]={right=true},[80]={down=true},[110]={down=true},[160]={a=true},[180]={x=true},[200]={r=true},[230]={l=true},[240]={a=true},[250]={start=true},[275]={start=true}}
local pausedFrame
emu.addEventCallback(function()
 local i={a=false,b=false,x=false,y=false,l=false,r=false,start=false,select=false,up=false,down=false,left=false,right=false}
 for at,buttons in pairs(steps)do if n>=at and n<at+(at==200 and 12 or 3) then for k,v in pairs(buttons)do i[k]=v end end end
 emu.setInput(i,0)
end,emu.eventType.inputPolled)
emu.addEventCallback(function()
 n=n+1
 if n>=30 and n<=75 then
  local tile=emu.read(2,emu.memType.snesSpriteRam)
  assert(tile==(word(0x16)==1 and 2 or 0),"Pose must address its own crop in shared OBJ memory")
 end
 if n==55 then assert(word(0x12)==1);pausedFrame=word(0x16)end
 if n==67 then assert(word(0x12)==1 and word(0x16)==(pausedFrame+1)%3,"Paused frame stepping")end
 if n==95 then assert(word(0x14)==1 and word(0x12)==0,"Ping pong selection")end
 if n==140 then assert(word(0x14)==2 and word(0x12)==1 and word(0x24)==1 and word(0x16)==2,"Non-looping end")end
 if n==164 then assert(word(0x24)==0 and word(0x12)==0,"Restart ended animation")end
 if n==190 then assert(word(0x1a)==1,"Palette variant")end
 if n==220 then assert(word(0x0a)==1,"Holding R changes resource once")end
 if n==245 or n==290 then local f=assert(io.open(dir..'/sprite-'..n..'.png','wb'));f:write(emu.takeScreenshot());f:close()end
 if n==300 then emu.stop(0)end
end,emu.eventType.endFrame)
